image: jangrewe/gitlab-ci-android

variables:
  ANDROID_COMPILE_SDK: "25"
  ANDROID_BUILD_TOOLS: "26.0.1"

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
  
cache:
  key: $CI_PROJECT_ID
  paths:
  - .gradle/

stages:
  - build+test

build+test:
  stage: build+test
  script:
    - ./gradlew assembleDebug
    - ./gradlew test
  artifacts:
    paths:
    - app/build/outputs/
    


